#!/bin/bash
set -e

function usage() {
    #TODO : rewrite Usage
    printf 'Usage: keras [-b/--bind dirname] [-s/--shell] [-p/--python filename] [-c commands] \n'
}

singularity="/usr/local/bin/singularity"
keras_img="/opt/singularity/keras-jskim.sif"
keras_backend="tensorflow"
cmd="help"
bpath="run"
pyexec="python3 --version"
cmexec="ls /mnt"
inname="keras"

while true;
do
    case "$1" in
        -p|--python)
            cmd="python"
            pyexec="python3 $2"
            shift
            shift
            break
            ;;
        -b|--bind)
            cmd=' '
            bpath="$2"
            shift
            shift
            break
            ;;
        -c|--command)
            cmd="cmd" 
            shift
            cmexec="$@"
            break
            ;;
        -s|--shell)
            cmd="shell" 
            shift
            break
            ;;
        -h|--help)
            cmd="help"
            shift
            break
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

export KERAS_BACKEND="$keras_backend"

# create directory for mount
mkdir -p ${HOME}/data/${bpath}

echo "$1"
case "$cmd" in
    python) 
            ${singularity} exec --bind ${HOME}/input:/input,${HOME}/data/${bpath}:/mnt --nv ${keras_img} ${pyexec}
        ;;
    cmd)
            ${singularity} exec --bind ${HOME}/input:/input,${HOME}/data/${bpath}:/mnt --nv ${keras_img} ${cmexec}
        ;;
    shell)
            ${singularity} shell --bind ${HOME}/input:/input,${HOME}/data/${bpath}:/mnt --nv ${keras_img} 
        ;;
    help)
        usage
        exit 0
        ;;
esac
