#!/bin/bash
POSITIONAL=()
set -e

function usage() {
    #TODO : rewrite Usage
    printf 'Usage: keras [-b/--bind dirname] [-s/--shell] [-p/--python filename] [-c commands] \n'
}

singularity="/usr/local/bin/singularity"
keras_img="/opt/singularity/keras-jskim.sif"
keras_backend="tensorflow"
cmd="help"
bpath="run"
pyexec="python3 --version"
toxexec="tox"
cmexec="ls /mnt"
inname="keras"

while [[ $# -gt 0 ]]
do
    cmd="$1"
    case $cmd in
        -b|--bind)
            bpath="$2"
            shift
            shift
            ;;
        -c|--command)
            cmd="cmd" 
            shift
            cmexec="$@"
            break
            ;;
        -p|--python)
            cmd="python"
            pyexec="python3 $2"
            shift
            shift
            break
            ;;
        -s|--shell)
            cmd="shell" 
            shift
            break
            ;;
        -t|--test)
            cmd="test"
            toxexec="tox"
            shift
            break
            ;;
        -h|--help)
            cmd="help"
            shift
            break
            ;;
        *)    # unknown option
            POSITIONAL+=("$1") # save it in an array for later
            shift # past argument
            ;;
    esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

export KERAS_BACKEND="$keras_backend"

# create directory for mount
mkdir -p ${HOME}/data/${bpath}

case $cmd in
    cmd)
        ${singularity} exec --bind ${HOME}/input:/input,${HOME}/data/${bpath}:/mnt --nv ${keras_img} ${cmexec}
        ;;
    python) 
        ${singularity} exec --bind ${HOME}/input:/input,${HOME}/data/${bpath}:/mnt --nv ${keras_img} ${pyexec}
        ;;
    shell)
        ${singularity} shell --bind ${HOME}/input:/input,${HOME}/data/${bpath}:/mnt --nv ${keras_img} 
        ;;
    test) 
        ${singularity} exec --bind ${HOME}/input:/input,${HOME}/data/${bpath}:/mnt --nv ${keras_img} ${toxexec}
        ;;
    help)
        usage
        exit 0
        ;;
esac
